// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function GetAllEnvironment():Promise<Array<objects.EnvironmentDto>>;

export function GetCurrentEnvironment(arg1:string,arg2:string):Promise<objects.EnvironmentDto>;
