// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function DeleteNamespaceByName(arg1:string):Promise<boolean>;

export function GetNamespace():Promise<Array<objects.NamespaceDto>>;

export function GetNamespaceByName(arg1:string):Promise<objects.NamespaceDto>;

export function GetNodeByName(arg1:string):Promise<objects.NodeDto>;

export function GetNodes():Promise<Array<objects.NodeDto>>;

export function UpdateNamespaceByName(arg1:string):Promise<boolean>;
