// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNamespaceByName(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['DeleteNamespaceByName'](arg1);
}

export function GetNamespace() {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespace']();
}

export function GetNamespaceByName(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespaceByName'](arg1);
}

export function GetNodeByName(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNodeByName'](arg1);
}

export function GetNodes() {
  return window['go']['middleware']['GeneralMiddleware']['GetNodes']();
}

export function UpdateNamespaceByName(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['UpdateNamespaceByName'](arg1);
}
