// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function GetNodes():Promise<Array<objects.NodeDto>>;
