// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNodeByName(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNodeByName'](arg1);
}

export function GetNodes() {
  return window['go']['middleware']['GeneralMiddleware']['GetNodes']();
}
