// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteIngressByName(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteIngressByName'](arg1, arg2);
}

export function DeleteServiceByName(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteServiceByName'](arg1, arg2);
}

export function GetIngressByName(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngressByName'](arg1, arg2);
}

export function GetIngresses(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngresses'](arg1);
}

export function GetServiceByName(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['GetServiceByName'](arg1, arg2);
}

export function GetServices(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetServices'](arg1);
}

export function Troubleshoot(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['Troubleshoot'](arg1, arg2);
}

export function UpdateIngressByName(arg1, arg2, arg3) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateIngressByName'](arg1, arg2, arg3);
}

export function UpdateServiceByName(arg1, arg2, arg3) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateServiceByName'](arg1, arg2, arg3);
}
