// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function GetIngressByName(arg1:string):Promise<objects.IngressDto>;

export function GetIngresses():Promise<Array<objects.IngressDto>>;

export function GetServiceByName(arg1:string):Promise<objects.ServiceDto>;

export function GetServices():Promise<Array<objects.ServiceDto>>;
