// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteIngressByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteIngressByName'](arg1);
}

export function DeleteServiceByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteServiceByName'](arg1);
}

export function GetIngressByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngressByName'](arg1);
}

export function GetIngresses() {
  return window['go']['middleware']['NetworkMiddleware']['GetIngresses']();
}

export function GetServiceByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetServiceByName'](arg1);
}

export function GetServices() {
  return window['go']['middleware']['NetworkMiddleware']['GetServices']();
}

export function UpdateIngressByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateIngressByName'](arg1);
}

export function UpdateServiceByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateServiceByName'](arg1);
}
