// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIngressByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngressByName'](arg1);
}

export function GetIngresses() {
  return window['go']['middleware']['NetworkMiddleware']['GetIngresses']();
}

export function GetServiceByName(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetServiceByName'](arg1);
}

export function GetServices() {
  return window['go']['middleware']['NetworkMiddleware']['GetServices']();
}
