// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteIngressByName(arg1:string):Promise<void>;

export function DeleteServiceByName(arg1:string):Promise<void>;

export function GetIngressByName(arg1:string):Promise<model.IngressDto>;

export function GetIngresses():Promise<Array<model.IngressDto>>;

export function GetServiceByName(arg1:string):Promise<model.ServiceDto>;

export function GetServices():Promise<Array<model.ServiceDto>>;

export function UpdateIngressByName(arg1:string):Promise<void>;

export function UpdateServiceByName(arg1:string):Promise<void>;
