// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function GetCommonParameters():Promise<Array<database.CommonParameterDto>>;

export function GetKubernetesParameters():Promise<Array<database.CommonParameterDto>>;
