// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommonParameters() {
  return window['go']['middleware']['ParameterMiddleware']['GetCommonParameters']();
}

export function GetHeaderParams(arg1) {
  return window['go']['middleware']['ParameterMiddleware']['GetHeaderParams'](arg1);
}

export function GetK8sObjects() {
  return window['go']['middleware']['ParameterMiddleware']['GetK8sObjects']();
}

export function GetKubernetesParameters() {
  return window['go']['middleware']['ParameterMiddleware']['GetKubernetesParameters']();
}
