// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPods(arg1) {
  return window['go']['middleware']['PodMiddleware']['GetPods'](arg1);
}
