// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function GetIngresses():Promise<Array<objects.IngressDto>>;

export function GetServices():Promise<Array<objects.ServiceDto>>;
