// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function DeletePersistentVolumeByName(arg1:string):Promise<boolean>;

export function GetPersistentVolumeByName(arg1:string):Promise<objects.PersistentVolumeDto>;

export function GetPersistentVolumes():Promise<Array<objects.PersistentVolumeDto>>;

export function UpdatePersistentVolumeByName(arg1:string):Promise<boolean>;
