// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPersistentVolumeByName(arg1) {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolumeByName'](arg1);
}

export function GetPersistentVolumes() {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolumes']();
}
