// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeletePersistentVolumeByName(arg1:string):Promise<void>;

export function GetPersistentVolumeByName(arg1:string):Promise<model.PersistentVolumeDto>;

export function GetPersistentVolumes():Promise<Array<model.PersistentVolumeDto>>;

export function UpdatePersistentVolumeByName(arg1:string):Promise<void>;
