// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeployments(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployments'](arg1);
}

export function GetPods(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPods'](arg1);
}
