// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDeployment(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['DeleteDeployment'](arg1);
}

export function GetDeployment(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployment'](arg1);
}

export function GetDeployments() {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployments']();
}

export function GetPod(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPod'](arg1);
}

export function GetPods() {
  return window['go']['middleware']['WorkloadMiddleware']['GetPods']();
}

export function RestartPod(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['RestartPod'](arg1);
}

export function UpdateDeployment(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdateDeployment'](arg1);
}

export function UpdatePod(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdatePod'](arg1);
}
