// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {objects} from '../models';

export function GetDeploymentByName(arg1:string):Promise<objects.DeploymentDto>;

export function GetDeployments(arg1:string):Promise<Array<objects.DeploymentDto>>;

export function GetPodByName(arg1:string):Promise<objects.PodDto>;

export function GetPods(arg1:string):Promise<Array<objects.PodDto>>;
