// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDeploymentByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['DeleteDeploymentByName'](arg1);
}

export function GetDeploymentByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeploymentByName'](arg1);
}

export function GetDeployments(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployments'](arg1);
}

export function GetPodByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPodByName'](arg1);
}

export function GetPods(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPods'](arg1);
}

export function RestartPodByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['RestartPodByName'](arg1);
}

export function UpdateDeploymentByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdateDeploymentByName'](arg1);
}

export function UpdatePodByName(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdatePodByName'](arg1);
}
