# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  set-up:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Set up VueJs
      uses: actions/setup-node@v2
      with:
        node-version: '18.13.0'

  dependency-go:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
    - name: Download Dependencies
      run: go mod download

    - name: Verify Dependencies
      run: go mod verify

  dependency-npm:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
    - name: Download Dependencies
      run: npm install

  testing:
    needs: [dependency-go, dependency-npm]
    runs-on: ubuntu-latest
    steps:
      - name: Vue Test
        run: cd frontend | npm run test:unit

      - name: Go Test
        run: go test ./... -v

